### ISSUE TITLE
уточнить куда ведет эта форма и нужна ли она нам

### ISSUE THREAD

**Issue by VladShumsky** [vadimpaj/meta.bel#10]
Мб с точки зрения cjm or seo она нужна... не знаю

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/0b9ed6f8-362a-4fe4-94b0-4dba43c358c7">

**Comment by vadimpaj** [comment]
Письмо с заявкой падает в ящик info@meta-center.by
