### ISSUE TITLE
раздел Новости

### ISSUE THREAD

**Issue by VladShumsky** [vadimpaj/meta.bel#15]
Сколько у нас планируется новостей? много, наверное. Может добавим навигацию в раздел? или разрывы страниц. что обычно делают?
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/ce5d691b-79d7-4428-bb8e-9758e545c0bd">

**Comment by vadimpaj** [comment]
Оно там всегда было, просто слишком мало новостей для пагинации
